const FamiliesSpreadsheet = [
  { label: 'Census Year', key: 'census_year' },
  { label: 'Census Visit', key: 'census_visit' },
  { label: 'Name Of Head', key: 'name_of_head' },
  { label: 'Total Members', key: 'total_members' },
  { label: 'Total Children', key: 'total_children' },
  { label: 'Address Province', key: 'address_province' },
  { label: 'Address Municipal', key: 'address_municipal' },
  { label: 'Address Barangay', key: 'address_barangay' },
  { label: 'Address Purok', key: 'address_purok' },
  { label: 'Address Street', key: 'address_street' },
  { label: 'Address Latitude', key: 'address_latitude' },
  { label: 'Address Longitude', key: 'address_longitude' },
  { label: 'Planning Methods', key: 'planning_methods' },
  { label: 'House Units', key: 'house_units' },
  { label: 'House Lights', key: 'house_lights' },
  { label: 'Water Supplies', key: 'water_supplies' },
  { label: 'Toilets', key: 'toilets' },
  { label: 'Garbage Disposals', key: 'garbage_disposals' },
  { label: 'Communication Facilities', key: 'communication_facilities' },
  { label: 'Transportation Facilities', key: 'transportation_facilities' },
  { label: 'Agricultural Products', key: 'agricultural_products' },
  { label: 'Poultry Chicken', key: 'poultry_chicken' },
  { label: 'Poultry Duck', key: 'poultry_duck' },
  { label: 'Poultry Geese', key: 'poultry_geese' },
  { label: 'Poultry Turkey', key: 'poultry_turkey' },
  { label: 'Livestock Pig', key: 'livestock_pig' },
  { label: 'Livestock Goat', key: 'livestock_goat' },
  { label: 'Livestock Sheep', key: 'livestock_sheep' },
  { label: 'Livestock Cow', key: 'livestock_cow' },
  { label: 'Livestock Carabao', key: 'livestock_carabao' },
  { label: 'Livestock Horse', key: 'livestock_horse' },
  { label: 'Other Livelihoods', key: 'other_livelihoods' },
  { label: 'Fishpond Area', key: 'fishpond_area' },
  { label: 'Owned Rice Field Area', key: 'owned_rice_field_area' },
  { label: 'Owned Corn Field Area', key: 'owned_corn_field_area' },
  { label: 'Unowned Rice Field Area', key: 'unowned_rice_field_area' },
  { label: 'Unowned Corn Field Area', key: 'unowned_corn_field_area' },
  { label: 'Unowned Lands', key: 'unowned_lands' },
  { label: 'Monthly Average Income', key: 'monthly_average_income' },
  { label: 'Created At', key: 'created_at' },
  { label: 'Updated At', key: 'updated_at' },
  { label: 'Last Updated By', key: 'last_updated_by' }
]

export default FamiliesSpreadsheet
