const ResidentSpreadsheet = [
  { label: 'Year', key: 'census_year' },
  { label: 'Visit No.', key: 'census_visit' },
  { label: 'Resident Name', key: 'name' },
  { label: 'Sex', key: 'sex' },
  { label: 'Age', key: 'age' },
  { label: 'Birthday', key: 'birthday' },
  { label: 'Place of Birth', key: 'place_of_birth' },
  { label: 'Nationality', key: 'nationality' },
  { label: 'Marital Status', key: 'marital_status' },
  { label: 'Ethnicity', key: 'ethnicity' },
  { label: 'Blood Type', key: 'blood_type' },
  { label: 'Occupation', key: 'occupation' },
  { label: 'Family Head', key: 'family_head' },
  { label: 'Household Head', key: 'household_head' },
  { label: 'Province', key: 'address_province' },
  { label: 'Municipality', key: 'address_municipal' },
  { label: 'Barangay', key: 'address_barangay' },
  { label: 'Purok', key: 'address_purok' },
  { label: 'Street', key: 'address_street' },
  { label: 'Latitude', key: 'address_latitude' },
  { label: 'Longitude', key: 'address_longitude' },
  { label: 'Solo Parent', key: 'solo_parent' },
  { label: 'Disability', key: 'disability' },
  { label: '4ps', key: 'member_of_4ps' },
  { label: 'IPs', key: 'member_of_ips' },
  { label: 'Highest School Level', key: 'educational_attainment' },
  { label: 'Currently Enrolled', key: 'enrolled' },
  { label: 'Health Cases', key: 'health_cases' },
  { label: 'Pregnant', key: 'pregnant' },
  { label: 'Lactating', key: 'lactating' },
  { label: 'Deaceased', key: 'deceased' },
  { label: 'Reason of Death', key: 'reason_of_death' },
  { label: 'Date Created', key: 'created_at' },
  { label: 'Date Updated', key: 'updated_at' },
  { label: 'Updated By', key: 'last_updated_by' }
]

export default ResidentSpreadsheet
